### PR TITLE
Updated profile collection folder , Updated readme.md and instruction

### PR DESCRIPTION
**Pull request by sb-decoder**
issue #97

### CODE REVIEW

**Comment by sb-decoder** [comment]
Please review this @DiyaVj

**Comment by sb-decoder** [comment]
It says that the branch has conflicts .Can you solve this?

**Review by DiyaVj — APPROVED** [review]
Profile Card Collection's readme is looking amazing! You have done a great job. I really appreciate your work and am happy to have a contributor like you. Thank you for your valuable contribution✨

**Comment by sb-decoder** [comment]
Thanks🙂

**Comment by sb-decoder** [comment]
There is two contributer's profile section in main  Readme.md . Move out one section.

**Comment by DiyaVj** [comment]
Yeah! thanks✨

**Pull request merged**
