### PR TITLE
Added Ritik Kumar Profile Card

### PR DESCRIPTION
**Pull request by RITIK0012**
Added Ritik Kumar Profile Card

### CODE REVIEW

**Comment by DiyaVj** [comment]
Hey @RITIK0012!
Your code files are not visible. please check it once

**Comment by RITIK0012** [comment]
@DiyaVj I have made the necessary changes and now the code might be visible to you. Please review it.

**Comment by DiyaVj** [comment]
Hey @RITIK0012 !
There are some changes in the repo. please sync the repo. Sorry for the inconvenience

**Comment by RITIK0012** [comment]
@DiyaVj Please Review again

**Review by DiyaVj — APPROVED** [review]
Thank you for your valuable contribution✨

**Pull request merged**
