### PR TITLE
Profile_card - Alit Indrawan

### PR DESCRIPTION
**Pull request by Alitindrawan24**

### CODE REVIEW

**Comment by DiyaVj** [comment]
Hey @Alitindrawan24 !
your code files are not visible. Kindly check them again.

**Comment by Alitindrawan24** [comment]
@DiyaVj Thanks I have update the PR

**Comment by DiyaVj** [comment]
Hey @Alitindrawan24!
There are some changes in the repo. please sync the repo. Sorry for the inconvenience

**Comment by Alitindrawan24** [comment]
@DiyaVj Hey I already sync the repo, can you check my PR again ? Thanks

**Review by DiyaVj — APPROVED** [review]
Thank you for your valuable contribution✨

**Pull request merged**
