### PR TITLE
Profile_card - Abhika Mittal

### PR DESCRIPTION
**Pull request by Abhika3021**

### CODE REVIEW

**Comment by DiyaVj** [comment]
Hey @Abhika3021 !
You have added your repository link instead of your hosted website link. Please add code files to the "Code" folder only and add your hosted website link to the README.md file inside the "Profile Card Collection folder.

**Comment by Abhika3021** [comment]
Didi, Can you please explain to me how to update because I tried but i'm
unable to do it.

**Comment by Abhika3021** [comment]
I have updated all the raised quries in the same repo.

**Comment by Abhika3021** [comment]
didi, updated in the same repo.

**Review by DiyaVj — APPROVED** [review]
Thankyou for your valuable contribution💜

**Pull request merged**
