### PR TITLE
Added profile with name Mehtab Khan

### PR DESCRIPTION
**Pull request by codeMehtab**

### CODE REVIEW

**Comment by codeMehtab** [comment]
Hi @ @DiyaVj Can you please review this PR #109 , thanks for your efforts for the opensource! :)

**Comment by DiyaVj** [comment]
Hey @codeMehtab! Thank you for contributing. Please add your name along with your profile card hosted link in the "profile card collection" folder.

**Comment by DiyaVj** [comment]
Hey @codeMehtab!
Your website link is not working.

**Comment by codeMehtab** [comment]
Hi @DiyaVj Thanks for taking time to review!
I have updated the changes, please review now :)

**Review by DiyaVj — APPROVED** [review]
Thank you for your valuable contribution✨

**Pull request merged**
