### PR TITLE
Profile_card - {Shashwat Srivastava}

### PR DESCRIPTION
**Pull request by Shashwat-srivastav**

### CODE REVIEW

**Comment by DiyaVj** [comment]
Hey @Shashwat-srivastav ! Please add your name and your hosted profile card website link in the profile card collection's Readme.

**Review by DiyaVj — APPROVED** [review]
Thankyou for your valuable contribution✨

**Comment by Shashwat-srivastav** [comment]
Thank you for your response this is my first contribution to opensource so
it is very valuable to me .

**Comment by DiyaVj** [comment]
I'm glad you chose this repo to start your hacktoberfest journey. Welcome to open source, good luck!👍🏻✨

**Comment by Shashwat-srivastav** [comment]
this contribution is excluded do you know why ??

**Pull request merged**
