### PR TITLE
Profile_card - Neha

### PR DESCRIPTION
**Pull request by InquisitiveMe15**
I have added my profile card. Kindly merge.

Thank you :)

### CODE REVIEW

**Comment by InquisitiveMe15** [comment]
Thank you :)

**Comment by DiyaVj** [comment]
Thank YOU for your valuable contribution❣

**Comment by DiyaVj** [comment]
Hey @InquisitiveMe15 !
Thank you for your valuable contribution. As I found, they(Hacktoberfest) are verifying the code in the PR so I recommend that you add your code to a "code folder" as well to avoid any consequences (your code should be in a folder named after you). Sincerely apologize for the inconvenience.

**Comment by InquisitiveMe15** [comment]
> Hey @InquisitiveMe15 ! Thank you for your valuable contribution. As I found, they(Hacktoberfest) are verifying the code in the PR so I recommend that you add your code to a "code folder" as well to avoid any consequences (your code should be in a folder named after you). Sincerely apologize for the inconvenience.

Yeah sure

**Comment by InquisitiveMe15** [comment]
@DiyaVj 
PR #54 

Kindly merge.
Thank you :)

**Pull request merged**
