### PR TITLE
Added my Profile Card 

### PR DESCRIPTION
**Pull request by submissivecoder69**
Added a profile card ^-^

### CODE REVIEW

**Comment by DiyaVj** [comment]
@submissivecoder69 Thank you for your valuable contribution. As I found, they(Hacktoberfest) are verifying the code in the PR so I recommend that you add your code to a "code folder" to avoid any consequences (your code should be in a folder named after you). Sincerely apologize for the inconvenience.

**Comment by submissivecoder69** [comment]
Added the code in the folder

**Comment by submissivecoder69** [comment]
Resolved conflicts

**Review by DiyaVj — APPROVED** [review]
Thankyou for your valuable contribution.💫

**Pull request merged**
