### PR TITLE
Adding My Card 

### PR DESCRIPTION
**Pull request by Pratham2301**
for hacktoberfest 2022

### CODE REVIEW

**Comment by DiyaVj** [comment]
@Pratham2301 Thank you for your valuable contribution. As I found, they(Hacktoberfest) are verifying the code in the PR so I recommend that you add your code to a "code folder" as well to avoid any consequences (your code should be in a folder named after you). Sincerely apologize for the inconvenience.

**Comment by Pratham2301** [comment]
Adding complete code

**Comment by Pratham2301** [comment]
Hello @DiyaVj ,
Is it okay now ????

**Comment by DiyaVj** [comment]
Hey @Pratham2301 !
I'm unable to access your code folder. Kindly check it once again.

**Pull request closed without merging**
