### PR TITLE
profile_card - Saransh Sinha

### PR DESCRIPTION
**Pull request by saranshsinhaa**

### CODE REVIEW

**Comment by DiyaVj** [comment]
@WraitH17 Thank you for your valuable contribution. As I found, they(Hacktoberfest) are verifying the code in the PR so I recommend that you add your code to a "code folder" as well to avoid any consequences (your code should be in a folder named after you). Sincerely apologize for the inconvenience.

**Comment by sarthakk24** [comment]
@DiyaVj  we have to add the whole repo which we used for hosting the card online or just the readme.md line in code folder ?
and the ones who's PR is already merged do they have to open new PR'S

**Comment by DiyaVj** [comment]
You need to add your name and the hosted profile card website to readme.me (inside the profile card archive folder) as well as your code files used in the template repo. Make sure you create a folder after your name inside "code" folder in this repo and add your code files inside that folder.

**Comment by sarthakk24** [comment]
@DiyaVj  Ohk and what about the already merged PR's do they also need to make one more pr's or leave as it is 
thanks for the help :)

**Comment by DiyaVj** [comment]
Kudos @WraitH17 ! You have done it the right way. I will update everyone about this soon. They need to create new PR to be considered for Hacktoberfest

**Comment by saranshsinhaa** [comment]
@DiyaVj Thanks for merging my PR!

**Comment by DiyaVj** [comment]
Hey @WraitH17!
Recently, I found out that this repo is put out by Hacktoberfest. can you please confirm? Because I didn't get any official information from hacktoberfest. It would be a great help.

**Comment by sarthakk24** [comment]
My PR got accepted i think so that this repo is still in hacktoberfest

**Pull request merged**
